
version: '3.8'

networks:
  payment-processor:
    external: true

services:
  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --tcp-backlog 511 --tcp-keepalive 300
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"
    networks:
      - payment-processor

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
    networks:
      - payment-processor

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: payment-processor:local
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "130MB"
    networks:
      - payment-processor

  api2:
    <<: *api
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "130MB"